services:
  db:
    image: postgres:16
    container_name: rpg_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .                     
    container_name: rpg_app
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"              
    environment:
      DATABASE_URL: postgresql+asyncpg://rpg:rpg@db:5432/rpg
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata: