"""added attributes to characters

Revision ID: 01035a7adb0b
Revises: caa3e755a49b
Create Date: 2026-03-13 19:28:11.227840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01035a7adb0b'
down_revision: Union[str, Sequence[str], None] = 'caa3e755a49b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('strength', sa.Integer(), server_default='10', nullable=False))
    op.add_column('characters', sa.Column('agility', sa.Integer(), server_default='10', nullable=False))
    op.add_column('characters', sa.Column('intelligence', sa.Integer(), server_default='10', nullable=False))
    op.add_column('characters', sa.Column('luck', sa.Integer(), server_default='10', nullable=False))
    op.add_column('characters', sa.Column('attribute_points', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'attribute_points')
    op.drop_column('characters', 'luck')
    op.drop_column('characters', 'intelligence')
    op.drop_column('characters', 'agility')
    op.drop_column('characters', 'strength')
    # ### end Alembic commands ###
