"""added attributes to items

Revision ID: 4a7b19f4d67e
Revises: 7c6a1dec2a81
Create Date: 2026-03-13 21:44:27.566036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a7b19f4d67e'
down_revision: Union[str, Sequence[str], None] = '7c6a1dec2a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('strength_bonus', sa.Integer(), nullable=False))
    op.add_column('items', sa.Column('agility_bonus', sa.Integer(), nullable=False))
    op.add_column('items', sa.Column('intelligence_bonus', sa.Integer(), nullable=False))
    op.add_column('items', sa.Column('luck_bonus', sa.Integer(), nullable=False))
    op.drop_column('items', 'str_bonus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('str_bonus', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('items', 'luck_bonus')
    op.drop_column('items', 'intelligence_bonus')
    op.drop_column('items', 'agility_bonus')
    op.drop_column('items', 'strength_bonus')
    # ### end Alembic commands ###
