"""added attributes to items

Revision ID: 7c6a1dec2a81
Revises: 01035a7adb0b
Create Date: 2026-03-13 20:55:19.882190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c6a1dec2a81'
down_revision: Union[str, Sequence[str], None] = '01035a7adb0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('item_type', sa.String(), nullable=False))
    op.add_column('items', sa.Column('is_equipped', sa.Boolean(), nullable=False))
    op.add_column('items', sa.Column('str_bonus', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_items_item_type'), 'items', ['item_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_item_type'), table_name='items')
    op.drop_column('items', 'str_bonus')
    op.drop_column('items', 'is_equipped')
    op.drop_column('items', 'item_type')
    # ### end Alembic commands ###
