"""added monsters

Revision ID: 89ba565bd802
Revises: 4a7b19f4d67e
Create Date: 2026-03-14 22:06:04.123513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ba565bd802'
down_revision: Union[str, Sequence[str], None] = '4a7b19f4d67e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('luck', sa.Integer(), nullable=False),
    sa.Column('exp_reward', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monsters_id'), 'monsters', ['id'], unique=False)
    op.create_index(op.f('ix_monsters_name'), 'monsters', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monsters_name'), table_name='monsters')
    op.drop_index(op.f('ix_monsters_id'), table_name='monsters')
    op.drop_table('monsters')
    # ### end Alembic commands ###
