"""removed intelligence from characters

Revision ID: cc4b689e0e27
Revises: d9dab36f480c
Create Date: 2026-03-17 21:38:07.024696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc4b689e0e27'
down_revision: Union[str, Sequence[str], None] = 'd9dab36f480c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'intelligence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('intelligence', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
