"""removed intelligence bonus from items

Revision ID: fe5d5f2c5bcf
Revises: cc4b689e0e27
Create Date: 2026-03-17 21:39:30.508400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe5d5f2c5bcf'
down_revision: Union[str, Sequence[str], None] = 'cc4b689e0e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'intelligence_bonus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('intelligence_bonus', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
